Merge changes for the Euro-Ameriga (mostly Amazonie and Beornia) to main
vic3-divergences/divergences pull request #243
Opened 2023-06-03 13:29 UTC by Kuri21079

2023-06-03 19:00 UTC, MadJamez submitted a review, later dismissed
[20:55:46][pdx_persistent_reader.cpp:252]: Error: "Unexpected token: state_muskogean_standard_of_living_add, near line: 1376" in file: "common/modifiers/content_1_modifiers.txt" near line: 1376
[20:55:46][pdx_persistent_reader.cpp:252]: Error: "Malformed token: -.05, near line: 8" in file: "common/modifiers/dvg_ama_modifiers.txt" near line: 8
[20:55:46][pdx_persistent_reader.cpp:252]: Error: "Unexpected token: interest_group_ig_petty_bougeoisie_pol_str_mult, near line: 42" in file: "common/modifiers/dvg_beo_modifiers.txt" near line: 42
[20:55:46][culture_type.cpp:126]: Missing localization key for name de_Saint-Andr in culture amazonien
[20:55:46][culture_type.cpp:126]: Missing localization key for name Yeng in culture qingqiuan
[20:55:46][technology_type.cpp:126]: Technology dvgaustralia has no ai_weight set, so AI can't research it
[20:55:47][pdx_persistent_reader.cpp:252]: Error: "Unexpected token: Nova, near line: 3" in file: "common/country_definitions/dvg_ameriga.txt" near line: 3
[20:55:48][pdx_persistent_reader.cpp:252]: Error: "Unexpected token: exists, near line: 1520" in file: "common/dynamic_country_names/dvg_dynamic_country_names.txt" near line: 1520
[20:55:48][pdx_persistent_reader.cpp:252]: Error: "Unexpected token: exists, near line: 1543" in file: "common/dynamic_country_names/dvg_dynamic_country_names.txt" near line: 1543
[20:55:48][gamedatabase.h:314]: Overriding entry 'TWT' for database 'common/dynamic_country_names' in ' file: common/dynamic_country_names/dvg_dynamic_country_names.txt line: 1593'
[20:55:48][gamedatabase.h:314]: Overriding entry 'BEO' for database 'common/dynamic_country_names' in ' file: common/dynamic_country_names/dvg_dynamic_country_names.txt line: 1798'
[20:55:49][pdx_persistent_reader.cpp:252]: Error: "Unexpected token: ai_chance, near line: 91" in file: "events/dvg_england.txt" near line: 93

2023-06-03 19:00 UTC, MadJamez commented on localization/english/dvg_names_l_english.yml
> +Falcone: "Falcone"
Duplicate localization key. Key 'Falcone' is defined in both 'localization/english/dvg_names_l_english.yml' and 'localization/english/dvg_names_l_english.yml'.

2023-06-05 03:14 UTC, Kuri21079 commented
Most of these should be resolved now, though I'm not so sure if the muskogean standard of living and the dvgaustralia tech relates to this branch?

2023-07-29 08:29 UTC, MadJamez requested changes
Can you also in general fix formatting? It's al over the place which makes it hard to spot issues an to review code.

2023-07-29 08:29 UTC, MadJamez commented on common/journal_entries/dvg_ameriga.txt
> +je_ameriga_unite = {
File 'common/journal_entries/dvg_ameriga.txt' should be in utf8-bom encoding

2023-07-29 08:29 UTC, MadJamez commented on common/journal_entries/dvg_ameriga.txt
> +	turmoil > 0.9
Inconsistent trigger scopes (country vs. state) in file: common/journal_entries/dvg_ameriga.txt line: 83

2023-07-29 08:29 UTC, MadJamez commented on common/journal_entries/dvg_beornia.txt
> +﻿
[10:25:22][gamedatabase.h:314]: Overriding entry 'je_ameriga_conquer' for database 'common/journal_entries' in ' file: common/journal_entries/dvg_beornia.txt line: 490'
[10:25:22][gamedatabase.h:314]: Overriding entry 'je_world_conquer' for database 'common/journal_entries' in ' file: common/journal_entries/dvg_beornia.txt line: 584'

2023-07-29 08:29 UTC, MadJamez commented on common/history/characters/0_dvg_tawantinsuyu.txt
> +		create_character = {
[10:25:33][jomini_script_system.cpp:263]: Script system error!
  Error: Failed to scope to culture by key 'Japanese'
  Script location: file: common/history/characters/0_dvg_tawantinsuyu.txt line: 79

[10:25:33][jomini_script_system.cpp:263]: Script system error!
  Error: Event target link 'cu' returned an unset scope
  Script location: file: common/history/characters/0_dvg_tawantinsuyu.txt line: 79

2023-08-15 10:32 UTC, MadJamez requested changes
This includes more then Beornia? Maybe try to keep it on different branches next time?
Also update the review description so its up to date with the actually content in here.

2023-08-15 10:32 UTC, MadJamez commented on localization/english/dvg_flavor_beornia_l_english.yml
> +dvg_beornia.1.f: "Beornia is by all metrics the youngest nation in Ameriga as it was only claimed by English settlers in the 17th century crossing the Odon river, living in small towns often unknown
Maybe make the first Beornia here also [ROOT.GetCountry.GetName] ?

2023-08-15 10:32 UTC, MadJamez commented on localization/english/country_flavor_text_l_english.yml
> + IRQ_FLAVOR_TEXT:0 "Iraq is a small breakaway state in the middle east, it was able to secure its independence in the collapse of the Ottoman Empire, who now only borders them along a small strip of
Seems to have some duplicate flavor text?

2023-08-15 10:32 UTC, MadJamez commented on localization/english/country_flavor_text_l_english.yml
>   REV_GENERIC_FLAVOR_TEXT:1 "Dissatisfied with the direction that the so-called organized government was taking, these revolutionaries have decided to take up arms to overthrow it. Will they succeed i
Duplicate localizations
[12:25:19][pdx_localize.cpp:279]: Duplicate localization key. Key 'IRQ_FLAVOR_TEXT' is defined in both 'localization/english/country_flavor_text_l_english.yml' and 'localization/english/country_flavor_text_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'DRV_ADJ' is defined in both 'localization/english/dvg_countries_l_english.yml' and 'localization/english/dvg_countries_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'Kiya' is defined in both 'localization/english/dvg_flavor_persia_l_english.yml' and 'localization/english/dvg_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_BAJA_CALIFORNIA_city' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_BAJA_CALIFORNIA_port' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_BAJA_CALIFORNIA_mine' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_BAJA_CALIFORNIA_farm' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_BAJA_CALIFORNIA_wood' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_DURANGO_city' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_DURANGO_mine' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_DURANGO_farm' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_DURANGO_wood' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_RIO_GRANDE_city' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_RIO_GRANDE_port' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_RIO_GRANDE_mine' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_RIO_GRANDE_farm' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_RIO_GRANDE_wood' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_ZACATECAS_city' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_ZACATECAS_mine' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_ZACATECAS_farm' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_ZACATECAS_wood' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_BAJIO_city' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_BAJIO_mine' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_BAJIO_farm' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_BAJIO_wood' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_OAXACA_city' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_OAXACA_farm' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_OAXACA_mine' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_OAXACA_wood' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_OAXACA_port' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_SINALOA_city' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_SINALOA_farm' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_SINALOA_mine' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_SINALOA_wood' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_SINALOA_port' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_JALISCO_city' is defined in both 'localization/english/dvg_hub_names_l_english.yml' and 'localization/english/hub_names_l_english.yml'.
[12:25:20][pdx_localize.cpp:279]: Duplicate localization key. Key 'HUB_NAME_STATE_JALISCO_port' is defined in [...]

2023-08-15 10:32 UTC, MadJamez commented on common/flag_definitions/dvg_flag_definitions.txt
> +CAU = { #Caucasia
"Unexpected token: CAU, near line: 3246" in file: "common/flag_definitions/dvg_flag_definitions.txt" near line: 3284

2023-08-15 10:32 UTC, MadJamez commented on common/history/characters/0_dvg_timurtash.txt
> +﻿CHARACTERS = {
[12:26:08][pdx_persistent_reader.cpp:252]: Error: "Wrong type parsed in create_character effect: Artuqid, near line: 24
Wrong type parsed in create_character effect: =, near line: 24" in file: "common/history/characters/0_dvg_timurtash.txt" near line: 35
[12:26:11][jomini_script_system.cpp:263]: Script system error!
  Error: set_owner_of_provinces effect [ Province 'x809040' crossing multiple state regions ]
  Script location: file: events/dvg_persia.txt line: 127

2023-08-15 10:32 UTC, MadJamez commented on common/history/characters/0_dvg_iraq.txt
> +﻿CHARACTERS = {
[12:26:11][character_templates_utils.cpp:29]: Invalid Ideology ideology_zaydani in  file: common/history/characters/0_dvg_iraq.txt line: 3
[12:26:11][character_templates_utils.cpp:29]: Can only do leader Ideologies in  file: common/history/characters/0_dvg_iraq.txt line: 3
[12:26:11][jomini_effect.cpp:128]: PostValidate of effect 'create_character' returned false at  file: common/history/characters/0_dvg_iraq.txt line: 3
[12:26:11][jomini_script_system.cpp:263]: Script system error!
  Error: add_ideology effect [ Invalid database object 'paternalistic' ]
  Script location: file: common/history/countries/0_dvg_middle_east.txt line: 97

[12:26:11][jomini_effect.cpp:128]: PostValidate of effect 'add_ideology' returned false at  file: common/history/countries/0_dvg_middle_east.txt line: 97
[12:26:11][jomini_script_system.cpp:263]: Script system error!
  Error: has_template trigger [ Invalid database object 'agitator_louise_michel' ]
  Script location: file: common/scripted_effects; create_paris_commune_characters line: 131

2023-08-15 14:44 UTC, closed without merging